### Login Success (Member)
POST http://localhost:8000/authentication/login
Content-Type: application/json

{
    "email": "Test User",
    "password": "asd123"
}

### Login Success (admin)
POST http://localhost:8000/authentication/login
Content-Type: application/json

{
    "email": "Administrator",
    "password": "admin123"
}

###############
#default access
GET http://localhost:8000/authentication/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMyODk5MDU1LCJleHAiOjE3MzI5MDA4NTV9.tH-gK1O62_D-i-BNKzccO3mdiySx763ggsiGyfnq82c

#####
#admin access
GET http://localhost:8000/admin/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMyODk5MDU1LCJleHAiOjE3MzI5MDA4NTV9.tH-gK1O62_D-i-BNKzccO3mdiySx763ggsiGyfnq82c

########################
#member access
GET http://localhost:8000/member/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMyODk5MDU1LCJleHAiOjE3MzI5MDA4NTV9.tH-gK1O62_D-i-BNKzccO3mdiySx763ggsiGyfnq82c