### Media Search (Simple)
GET http://localhost:8000/media/search
Content-Type: application/json

{
    "value": "Book",
    "isAdvanced": false,
    "searchBy": "all",
    "mediaTypes": ""
}

### Media Search (Advanced)
GET http://localhost:8000/media/search
Content-Type: application/json

{
    "value": "Book",
    "isAdvanced": true,
    "searchBy": "title",
    "mediaTypes": ""
}

###############
