### Login Success (Member)
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "Test User",
    "password": "asd123"
}

### Login Success (admin)
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "Administrator",
    "password": "admin123"
}

###############
#default access
GET http://localhost:8000/auth/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM1MTY1ODA2LCJleHAiOjE3MzUxNjc2MDZ9.r6_NvkmavKD_Qdof3_8y5fWT_2V-5di0BNInhDRT6po

#####
#admin access
GET http://localhost:8000/admin/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM1MTY1ODA2LCJleHAiOjE3MzUxNjc2MDZ9.r6_NvkmavKD_Qdof3_8y5fWT_2V-5di0BNInhDRT6po

########################
#member access
GET http://localhost:8000/member/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJBZG1pbmlzdHJhdG9yIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM1MTY1ODA2LCJleHAiOjE3MzUxNjc2MDZ9.r6_NvkmavKD_Qdof3_8y5fWT_2V-5di0BNInhDRT6po