### Media Search (Simple)
POST  http://localhost:8000/media/search
Content-Type: application/json

{
    "value": "d",
    "isAdvanced": false,
    "searchBy": "all",
    "mediaTypes": {
        "all": true,
        "book": true,
        "periodical": true,
        "multimedia": true
    }
}

### Media Search (Advanced)
POST  http://localhost:8000/media/search
Content-Type: application/json

{
    "value": "d",
    "isAdvanced": true,
    "searchBy": "all",
    "mediaTypes": {
        "all": false,
        "book": true,
        "periodical": false,
        "multimedia": true
    }
}

################################################################
###################### Fail Tests ##############################
################################################################
### JSON Syntax Error
POST  http://localhost:8000/media/search
Content-Type: application/json

{
    "value": "d",
    "isAdvanced": true,
    "searchBy": "all",
    "mediaTypes": {
        "all": false,
        "book": true,
        "periodical": false,
        "multimedia": true
    }""
}