exports.mockMediaData = [
    {
      mediaID: 1,
      mediaName: '1984',
      creator: 'George Orwell',
      publisher: 'Secker & Warburg',
      year: 1949,
      mediaType: 'Book',
    },
    {
      mediaID: 2,
      mediaName: 'Time Magazine',
      creator: 'Henry Luce',
      publisher: 'Time Inc.',
      year: 1923,
      mediaType: 'Periodical',
    },
    {
      mediaID: 3,
      mediaName: 'The Dark Knight',
      creator: 'Christopher Nolan',
      publisher: 'Warner Bros.',
      year: 2008,
      mediaType: 'Multimedia',
    },
    {
      mediaID: 4,
      mediaName: 'Breaking Bad',
      creator: 'Vince Gilligan',
      publisher: 'AMC',
      year: 2008,
      mediaType: 'Multimedia',
    },
    {
      mediaID: 5,
      mediaName: 'National Geographic',
      creator: 'Various',
      publisher: 'National Geographic Society',
      year: 1888,
      mediaType: 'Periodical',
    },
    {
      mediaID: 6,
      mediaName: 'The Matrix',
      creator: 'Lana Wachowski, Lilly Wachowski',
      publisher: 'Warner Bros.',
      year: 1999,
      mediaType: 'Multimedia',
    },
    {
      mediaID: 7,
      mediaName: 'The Great Gatsby',
      creator: 'F. Scott Fitzgerald',
      publisher: 'Charles Scribner\'s Sons',
      year: 1925,
      mediaType: 'Book',
    },
    {
      mediaID: 8,
      mediaName: 'The Office (US)',
      creator: 'Greg Daniels',
      publisher: 'NBC',
      year: 2005,
      mediaType: 'Multimedia',
    },
    {
      mediaID: 9,
      mediaName: 'The New York Times',
      creator: 'Adolph Ochs',
      publisher: 'The New York Times Company',
      year: 1851,
      mediaType: 'Periodical',
    },
    {
      mediaID: 10,
      mediaName: 'The Godfather',
      creator: 'Francis Ford Coppola',
      publisher: 'Paramount Pictures',
      year: 1972,
      mediaType: 'Multimedia',
    },
    {
      mediaID: 11,
      mediaName: 'Sapiens: A Brief History of Humankind',
      creator: 'Yuval Noah Harari',
      publisher: 'Harvill Secker',
      year: 2011,
      mediaType: 'Book',
    },
    {
      mediaID: 12,
      mediaName: 'Wired Magazine',
      creator: 'Louis Rossetto, Jane Metcalfe',
      publisher: 'Condé Nast',
      year: 1993,
      mediaType: 'Periodical',
    },
  ];